let CREATED_AT = "CREATED_AT",
    ID = "ID",
    INVENTORY_TOTAL = "INVENTORY_TOTAL",
    PRODUCT_TYPE = "PRODUCT_TYPE",
    PUBLISHED_AT = "PUBLISHED_AT",
    RELEVANCE = "RELEVANCE",
    TITLE = "TITLE",
    VENDOR = "VENDOR",
    UPDATED_AT = "UPDATED_AT"

export { CREATED_AT, ID, INVENTORY_TOTAL, PRODUCT_TYPE, PUBLISHED_AT, RELEVANCE, TITLE, UPDATED_AT, VENDOR }